### ISSUE TITLE
Failed to process

### ISSUE THREAD

**Issue by visherandro** [dimorinny/show-case-card-view#5]
![screen shot 2017-10-21 at 5 42 27 pm](https://user-images.githubusercontent.com/13933254/31851630-5abe126c-b687-11e7-9b5e-ff7fb55f75c2.png)

**Comment by ik-javier** [comment]
I have same bug in android studio 3.0 stable version
Any fix to solve problem?

**Comment by ik-javier** [comment]
i have same bug in android studio 3.0 stable version

**Comment by j2emanue** [comment]
i have the same issue .the library is not usable now.

**Comment by dimorinny** [comment]
This problem was fixed in 0.0.4 version.
Update please for normal use.
