### ISSUE TITLE
changing radius for ShowCaseStepDisplayer

### ISSUE THREAD

**Issue by vibhuti1403** [dimorinny/show-case-card-view#6]
Is there any way to change the default radius in ShowCaseStepDisplayer?

**Comment by vinaychenna** [comment]
How to display the showcase on overflow menu item?

**Comment by vinaychenna** [comment]
I used the showcase inside the dismiss of another showcase. The first  showcase is displayed correctly, second one is displayed in wrong position. Can you please help on this.

**Comment by JulianEggers** [comment]
@vinaychenna 
Calling the second Showcast within the dismiss of the first works for me.
However, when using a recyclerview the showcast sometimes appears at a wrong position. 

`W/View: requestLayout() improperly called by ru.dimorinny.showcasecard.ShowCaseView{ffb62c5 V.ED..... ......I. 0,0-0,0} during layout: running second layout pass`
